extends:
  - 'stylelint-config-standard'
  - 'stylelint-config-recess-order'

plugins:
  - 'stylelint-use-logical-spec'

rules:
  selector-class-pattern:
    - '^[a-z][a-zA-Z0-9]+$' # camelCase
    - resolveNestedSelectors: true
  liberty/use-logical-spec: true
